[[build]]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[redirects]]
  from = "/api/*"
  to = "https://your-railway-backend.up.railway.app/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"